name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mstksg/get-package@v1
      with:
        apt-get: pkg-config libcmocka-dev

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make debug

    - name: Run Tests
      run: make test